# config_local.yaml

# Study-specific identifiers
study_id: "ICB_Gide" # ICB_<author or study name>
cancer_type: "Melanoma"

# Treatment type (can be changed based on your cohort)
# Examples: "PD-1/PD-L1", "CTLA-4", "IO+combo"
treatment_type: "PD-1/PD-L1"

# Input/output directories
dir_in: "data/procdata"     # Processed input .rda file location
dir_out: "data/results"     # Output results directory for this center

# Input data object names in .rda file
expr: "dat$ICB"
signature: "dat$signature"
signature_info: "dat$sig.info"

# Signature scoring settings
signature_scoring:
  missing.perc: 0.5
  const.int: 0.001
  n.cutoff: 15
  sig.perc: 0.8

# Logistic regression parameters
logreg:
 n0.cutoff: 3
 n1.cutoff: 3

# Output filenames (saved under dir_out)
output_files:
  scores: "sig_score.rda"
  correlation: "sig_pcor.rda"
  survival_os: "sig_os.rda"
  survival_pfs: "sig_pfs.rda"
  logreg_response: "sig_logreg.rda"
