# config_proc.yaml

# Study-specific identifiers
study_icb: "ICB_Gide" # ICB_<author or study name>
cancer_type: "Melanoma"

# Treatment type (can be changed based on your cohort)
# Examples: "PD-1/PD-L1", "CTLA-4", "IO+combo"
treatment_type: "PD-(L)1"

# Input/output directories
dir_in: "data/rawdata"     # raw input .rds file location
dir_out: "data/procdata"     # Processed input .rda file location

